### ISSUE TITLE
Birthday icon in  calendar .

### ISSUE THREAD

**Issue by aliwaleed1** [codescalers/CSHR#197]
the birthday of any employee show below the calendar not in day cell ,like meeting for example
![Birthday](https://github.com/codescalersinternships/CSHR/assets/138436398/2f46d491-587f-4928-9963-b548ccb59dbd)

**Comment by zaelgohary** [comment]
Done in https://github.com/codescalers/CSHR/issues/265

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
