### ISSUE TITLE
exponential number in Update User Vacation Balance

### ISSUE THREAD

**Issue by aliwaleed1** [codescalers/CSHR#198]
when we need to exponential number in Update User Vacation Balance , must write number in this three field (Annual leaves , Leave excuses ,Emergency leaves) ,when I try write exponential number in any field the submit button the submit button be clickable ,then we can update successfully
![update vacation submit](https://github.com/codescalersinternships/CSHR/assets/138436398/b3c30d98-3e5d-4ac4-b241-e790f5e4e7ad)
but after click on submit button and go to user to check if updated, nothing change of all field ,not in the only field  have exponential number ,
![after update](https://github.com/codescalersinternships/CSHR/assets/138436398/18acea69-3852-4a9a-a055-c436e9e6409e)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
