### ISSUE TITLE
 invisible element in add user skills

### ISSUE THREAD

**Issue by aliwaleed1** [codescalers/CSHR#202]
when user need to add skill ,he need to write skill first ,but the submit button after that not be clickable ,the user need to click on the invisible element to see it in "Add new skills" then can click on submit button .
![add skills  bug](https://github.com/codescalersinternships/CSHR/assets/138436398/d9b2041f-5c33-4513-bd64-ec9f950b1090)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
