### ISSUE TITLE
CSHR

### ISSUE THREAD

**Issue by rkhamis** [codescalers/CSHR#9]
The idea of CSHR is to have an HR management system that allows both **localized** management and **global** overview.

For a company that has more than 1 office, that means that the entire organization should be able to:
 -  share a calendar showing approved vacations (and birthdays)
 - search for a user and see their public information
 - search for a skillset and find all matching users with this skillset

But the system should also act locally, defining an admin for each location.
Admins in different locations do not share admin rights. meaning an admin of a location can only admin rights in that location only.

There are three currently defined levels of access:
 - user (anyone that is part of the orangization)
 - supervisor (each user has a defined supervisor)
 - admin (an admin of a location, where some users are defined)

### Features of CSHR
 - login via threefoldconnect (see #1 )
 - global calendar (see #8 )
 - applying for vacations (see #3 )
 - approving/denying requests (see #5)
 - requesting docs from HR (see #4 )
 - reminders for different evaluations (see #7)
 - automatically and on-demand generate reports (see #6 )

**Comment by omar-sherif9992** [comment]
Figma:
  - Made Half of the number of Pages with Zeina

Backend:
- Model
  - User 
  - Request 
  - Vacation 
  - meeting 
  - event
- serializer
  - User 
- views
  - User
- pagination

- made fixes from  in backend for info needed for the Frontend

Frontend :
  - setup
     - Intialized the project
     - tsconfig
     - eslint
     - prettier
     - Routes
     - .env
     - Introductory video for future development so soon to be made at the end of the project
   
  - components :(each component is customizable & has flags)
    - paginated table
    - modal
    - input
    - toast (popup)
    - submit button
    - loading and error component
    - pagination
    - multiselect & one select (multiple=false)
    - datepicker
    - sidebar & navbar
  
 - pages
   - Calendar landing page (datepicker, main calendar, 3 forms with 2 modals and popup and error,filters, 4 types modals  and made for it 4 big parsers)
   -  team page
   - all users page 
   - vacation page design (with Zeina)
   - login page design (with Alia)
   - User profile page
  - evaluation Page
  - Error 404 page
  - footer

- Services
  - OOP Axios requests
      - home
      - offices
      - user
      - users
  - authentication utils
  - verification utils

- stores 
- types  in typescript

- gave sessions
  - How to use Figma 
  - individual sessions to each one to get them started
  - Axios OOP session 
  - types in typescript
  - best practices to follow
  - many telegram notes and updates


- debugging
  - with every one problem daily

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
